name: Github Pages Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    env: 
      CI: false

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build
        run: CI=false npm install && npm run build

      - name: Check Git installation
        run: git --version

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./build
          verbose: true



     